name: 'README AI'
description: 'Auto-generate README from commits'

inputs:
  openai-api-key:
    description: 'OpenAI API key for generating README content'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OPENAI_API_KEY: ${{ inputs.openai-api-key }}